### ISSUE TITLE
Two Model files inside riskModel Packages.

### ISSUE THREAD

**Issue by shahakshay94** [prashantp995/AdvanceProgrammingPracticesRiskGame#1]
For continent, countries, and map I can see two class files such as Continent, ContinentModel and so on. So is it created deliberately for other purposes? Or we can merge these kinds of classes into one?

**Comment by prashantp995** [comment]
it is created to reduce the complexity of the code . The continent class is nothing but POJO class and ContinentModel is for the business logic part. And yes, we can merge both into one class.
