### ISSUE TITLE
JUnit for method with object as return type.

### ISSUE THREAD

**Issue by shahakshay94** [prashantp995/AdvanceProgrammingPracticesRiskGame#2]
https://github.com/prashantp995/AdvanceProgrammingPracticesRiskGame/blob/f75dbc170ab5617f6788b9b8594099a97c755c8f/RiskGame/src/riskModels/map/MapModel.java#L115

Now I am facing some issue regarding creating the test case for this particular method where a return type is an object. Can we do this in some another way?

**Comment by prashantp995** [comment]
As discussed, we can not do it now. can mark as future release
